#Following is simply prediction of GPA based on SAT and Rndom 1 2 3 variable

In [1]:
#Step 1 is simply importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [3]:
#import LinearRegression from sklearn
from sklearn.linear_model import LinearRegression

In [5]:
#impot StanderdScaller from sklearn
from sklearn.preprocessing import StandardScaler

In [6]:
#Importing data from system stored in .csv file
raw_data = pd.read_csv("C:/Users/Chi_12345/The Data Science Course 2021 - All Resources/05/S34_L221/1.02. Multiple linear regression.csv")

In [7]:
raw_data.head(10)

    SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83
5  1670           1  2.91
6  1764           2  3.00
7  1764           1  3.00
8  1792           2  3.01
9  1850           3  3.01

#Define inputs and targets for model

In [8]:
data = raw_data.copy()
targets = data["GPA"]
inputs = data[["SAT","Rand 1,2,3"]]

In [9]:
targets

0     2.40
1     2.52
2     2.54
3     2.74
4     2.83
      ...
79    3.71
80    3.71
81    3.73
82    3.76
83    3.81
Name: GPA, Length: 84, dtype: float64

In [10]:
inputs

     SAT  Rand 1,2,3
0   1714           1
1   1664           3
2   1760           3
3   1685           3
4   1693           2
..   ...         ...
79  1936           3
80  1810           1
81  1987           3
82  1962           1
83  2050           2

[84 rows x 2 columns]

In [17]:
#Followind methods are used for standerdization
scaler = StandardScaler()
scaler.fit(inputs)
scaler_inputs = scaler.transform(inputs)
scaler_inputs

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984, -1.24637147],
       [-0.4934606 , -0.07002087],
       [-0.73406132, -1.24637147],
       [ 0.85390339, -1.24637147],
       [-0.67631715, -1.24637147],
       [ 0.09360513,  1.10632974],
       [ 0.33420585, -0.07002087],
       [ 0.03586096, -0.07002087],
       [-0.35872421,  1.10632974],
       [ 1.04638396,  1.10632974],
       [-0.65706909,  1.10632974],
       [-0.13737155, -0.07002087],
       [ 0.18984542,  1.10632974],
       [ 0.04548499, -1.24637147],
       [ 1.1618723 ,  1.10632974],
       [-1.37887123, -1.24637147],
       [ 1.39284898, -1.24637147],
       [ 0.76728713, -0.07002087],
       [-0.20473975, -0.07002087],
       [ 1.06563201, -1.24637147],
       [ 0.11285319, -1.24637147],
       [ 1.28698467,  1.10632974],
       [-0.41646838,  1.10632974],
       [ 0.09360513, -1.24637147],
       [ 0.59405462, -0.07002087],
       [-2.03330517, -0.07002087],
       [ 0.32458182, -1.24637147],
       [ 0.40157405, -1.24637147],
       [-1.10939843, -0.07002087],
       [ 1.03675993, -1.24637147],
       [-0.61857297, -0.07002087],
       [ 0.44007016, -0.07002087],
       [ 1.14262424, -1.24637147],
       [-0.35872421,  1.10632974],
       [ 0.45931822,  1.10632974],
       [ 1.88367444,  1.10632974],
       [ 0.45931822, -1.24637147],
       [-0.12774752, -0.07002087],
       [ 0.04548499,  1.10632974],
       [ 0.85390339, -0.07002087],
       [ 0.15134931, -0.07002087],
       [ 0.8250313 ,  1.10632974],
       [ 0.84427936,  1.10632974],
       [-0.64744506, -1.24637147],
       [ 1.24848856, -1.24637147],
       [ 0.85390339,  1.10632974],
       [ 1.69119387,  1.10632974],
       [ 1.6334497 ,  1.10632974],
       [ 1.46021718, -1.24637147],
       [ 1.68156984, -0.07002087],
       [-0.02188321,  1.10632974],
       [ 0.87315144,  1.10632974],
       [-0.33947615, -1.24637147],
       [ 1.3639769 ,  1.10632974],
       [ 1.12337618, -1.24637147],
       [ 1.97029069, -0.07002087]])

#Lets fit LinearRegression model

In [18]:
reg = LinearRegression()
reg.fit(scaler_inputs , targets)

LinearRegression()

In [24]:
#lets Create Summary Table for regression model
summary_table = pd.DataFrame(data = [["Bias"],["SAT"],["Rand 1,2,3"]] , columns = ['Features'])
summary_table["Weights"] = reg.intercept_ , reg.coef_[0] , reg.coef_[1]
summary_table

     Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [35]:
#Now lets find p-values and F-values for features contribution to predict GPA
from sklearn.feature_selection import f_regression
p_values = f_regression(inputs , targets)[1]
f_values = f_regression(inputs , targets)[0]

In [37]:
Table = pd.DataFrame(data = [["SAT"],["Rand 1,2,3"]] , columns = ['Features'])
Table["p_value"] = p_values
Table["f_value"] = f_values
Table

     Features       p_value    f_value
0         SAT  7.199518e-11  56.048048
1  Rand 1,2,3  6.762914e-01   0.175584

#Conclusion

In [38]:
#Removing rand 1,2,3 wont effect linear model as it has p_value greater than 0.05